In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import pandas as pd

file = "Attendance-Sheet-2022-2023.xlsx"

sheets = ["Apr 2022", "May 2022", "June 2022"]

all_data = []

for sheet in sheets:

    df = pd.read_excel(file, sheet_name=sheet)

    # Rename columns
    df.rename(columns={
        "AtliQ": "Employee Code",
        "Unnamed: 1": "Name"
    }, inplace=True)

    # Remove unwanted columns
    remove_cols = [
        'Total Present Days',
        'Present',
        'Work from home ',
        'Paid Leave ',
        'Sick Leave ',
        'Birthday Leave ',
        'Floting festival leave ',
        'Bereavement Leave',
        'Leave without pay',
        'Weekly Off',
        'Holidays Off',
        'Menstrual Leave'
    ]

    df = df.drop(columns=remove_cols, errors='ignore')

    #   # Remove duplicate header rows
    df = df[df["Employee Code"] != "Employee Code"]

    # Convert wide to long
    df = df.melt(
        id_vars=["Employee Code", "Name"],
        var_name="Date",
        value_name="Status"
    )

    # Add month
    df["Month"] = sheet

    all_data.append(df)

# Combine all sheets
final_df = pd.concat(all_data, ignore_index=True)

final_df

C:\Users\deepa\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\deepa\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():
C:\Users\deepa\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():

,Employee Code,Name,Date,Status,Month
0,Employee Code,Name,2022-04-01 00:00:00,2022-04-01 00:00:00,Apr 2022
1,Atq -406,Thanos Thakur,2022-04-01 00:00:00,P,Apr 2022
2,Atq -462,Jarvis Singh,2022-04-01 00:00:00,P,Apr 2022
3,Atq -411,Nevaeh Waller,2022-04-01 00:00:00,P,Apr 2022
4,Atq -398,Bo Cordova,2022-04-01 00:00:00,P,Apr 2022
...,...,...,...,...,...
7714,Atq -334,Charity Singleton,2022-06-01 00:00:00.1,NaT,June 2022
7715,Atq -414,Mckayla Miles,2022-06-01 00:00:00.1,NaT,June 2022
7716,Atq -389,Julien Hamilton,2022-06-01 00:00:00.1,NaT,June 2022
7717,Atq -385,Alyson Huber,2022-06-01 00:00:00.1,NaT,June 2022
7718,Atq -348,Zaiden Wheeler,2022-06-01 00:00:00.1,NaT,June 2022

In [3]:
print(final_df.columns.tolist())

['Employee Code', 'Name', 'Date', 'Status', 'Month']

In [4]:
# First row remove
final_df = final_df[1:]

In [5]:
final_df

     Employee Code               Name                   Date Status      Month
1         Atq -406      Thanos Thakur    2022-04-01 00:00:00      P   Apr 2022
2         Atq -462       Jarvis Singh    2022-04-01 00:00:00      P   Apr 2022
3         Atq -411      Nevaeh Waller    2022-04-01 00:00:00      P   Apr 2022
4         Atq -398         Bo Cordova    2022-04-01 00:00:00      P   Apr 2022
5         Atq -438    Mekhi Singleton    2022-04-01 00:00:00      P   Apr 2022
...            ...                ...                    ...    ...        ...
7714      Atq -334  Charity Singleton  2022-06-01 00:00:00.1    NaT  June 2022
7715      Atq -414      Mckayla Miles  2022-06-01 00:00:00.1    NaT  June 2022
7716      Atq -389    Julien Hamilton  2022-06-01 00:00:00.1    NaT  June 2022
7717      Atq -385       Alyson Huber  2022-06-01 00:00:00.1    NaT  June 2022
7718      Atq -348     Zaiden Wheeler  2022-06-01 00:00:00.1    NaT  June 2022

[7718 rows x 5 columns]

In [6]:
# here check the null values
final_df.isnull().sum()

Employee Code       0
Name                0
Date                0
Status           1165
Month               0
dtype: int64

In [7]:
# Drop the Null values
final_df.dropna(inplace=True)

C:\Users\deepa\AppData\Local\Temp\ipykernel_14132\2709626079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace=True)

In [8]:
final_df

     Employee Code                 Name                 Date Status      Month
1         Atq -406        Thanos Thakur  2022-04-01 00:00:00      P   Apr 2022
2         Atq -462         Jarvis Singh  2022-04-01 00:00:00      P   Apr 2022
3         Atq -411        Nevaeh Waller  2022-04-01 00:00:00      P   Apr 2022
4         Atq -398           Bo Cordova  2022-04-01 00:00:00      P   Apr 2022
5         Atq -438      Mekhi Singleton  2022-04-01 00:00:00      P   Apr 2022
...            ...                  ...                  ...    ...        ...
7587      Atq -405           Chris Frye  2022-06-30 00:00:00    WFH  June 2022
7619      Atq -459       Leslie Navarro  2022-06-30 00:00:00    WFH  June 2022
7621      Atq -350  Alexander Davenport  2022-06-30 00:00:00    WFH  June 2022
7623      Atq -374    Kaley Fitzpatrick  2022-06-30 00:00:00    LWP  June 2022
7635      Atq -348       Zaiden Wheeler  2022-06-30 00:00:00    WFH  June 2022

[6553 rows x 5 columns]

In [9]:
final_df.shape

(6553, 5)

In [10]:
final_df.columns

Index(['Employee Code', 'Name', 'Date', 'Status', 'Month'], dtype='object')

In [11]:
# remove the timezone from the date 
final_df["Date"]=pd.to_datetime(final_df["Date"]).dt.date

C:\Users\deepa\AppData\Local\Temp\ipykernel_14132\1494889609.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df["Date"]=pd.to_datetime(final_df["Date"]).dt.date

In [12]:
final_df

     Employee Code                 Name        Date Status      Month
1         Atq -406        Thanos Thakur  2022-04-01      P   Apr 2022
2         Atq -462         Jarvis Singh  2022-04-01      P   Apr 2022
3         Atq -411        Nevaeh Waller  2022-04-01      P   Apr 2022
4         Atq -398           Bo Cordova  2022-04-01      P   Apr 2022
5         Atq -438      Mekhi Singleton  2022-04-01      P   Apr 2022
...            ...                  ...         ...    ...        ...
7587      Atq -405           Chris Frye  2022-06-30    WFH  June 2022
7619      Atq -459       Leslie Navarro  2022-06-30    WFH  June 2022
7621      Atq -350  Alexander Davenport  2022-06-30    WFH  June 2022
7623      Atq -374    Kaley Fitzpatrick  2022-06-30    LWP  June 2022
7635      Atq -348       Zaiden Wheeler  2022-06-30    WFH  June 2022

[6553 rows x 5 columns]

In [13]:
# final_df.to_excel("Cleaned_Attendance1.xlsx", index=False)

In [14]:
attendance=(
    final_df.groupby("Name")["Status"].apply(lambda x:(x=="P").mean()*100)
    .reset_index(name="attendance %")
)
attendance

                   Name  attendance %
0          Aditya Walls     56.521739
1           Adriel Pace     64.197531
2          Adyson Moyer     60.493827
3   Alexander Davenport      0.000000
4          Alyson Huber     61.904762
..                  ...           ...
95        Tucker Austin     61.904762
96        Weston Horton     61.728395
97         Will Mahoney     62.962963
98         Xiomara Ruiz     62.962963
99       Zaiden Wheeler      0.000000

[100 rows x 2 columns]

In [15]:
# WFH Count
wfh = final_df[final_df["Status"] == "WFH"]

wfh

     Employee Code                 Name        Date Status      Month
12        Atq -443       Lyric Bartlett  2022-04-01    WFH   Apr 2022
24        Atq -396            Joel Cruz  2022-04-01    WFH   Apr 2022
39        Atq -405           Chris Frye  2022-04-01    WFH   Apr 2022
54        Atq -485         Gregory Carr  2022-04-01    WFH   Apr 2022
55        Atq -452        Ayanna Atkins  2022-04-01    WFH   Apr 2022
...            ...                  ...         ...    ...        ...
7552      Atq -348       Zaiden Wheeler  2022-06-29    WFH  June 2022
7587      Atq -405           Chris Frye  2022-06-30    WFH  June 2022
7619      Atq -459       Leslie Navarro  2022-06-30    WFH  June 2022
7621      Atq -350  Alexander Davenport  2022-06-30    WFH  June 2022
7635      Atq -348       Zaiden Wheeler  2022-06-30    WFH  June 2022

[450 rows x 5 columns]

In [16]:
# Sick Leave Analysis
sl = final_df[final_df["Status"] == "SL"]

print(sl.head())

     Employee Code               Name        Date Status     Month
489       Atq -404         Ana Little  2022-04-07     SL  Apr 2022
497       Atq -440     Mckayla Parker  2022-04-07     SL  Apr 2022
997       Atq -331     Jonah Hamilton  2022-04-13     SL  Apr 2022
1469      Atq -370          Ella Roth  2022-04-19     SL  Apr 2022
1645      Atq -398  Salvatore Hendrix  2022-04-21     SL  Apr 2022

In [17]:
# Top employees present

top=(
    final_df[final_df["Status"]=="P"]
    .groupby("Name").size().sort_values(ascending=False)
    .reset_index(name="top employee")
)
top

                Name  top employee
0        Isiah Small            56
1      Thanos Thakur            56
2       Jarvis Singh            56
3           Loki Lal            55
4       Tori Shannon            55
..               ...           ...
87   Janelle Raymond             7
88  Isabella Pittman             7
89       Shea Zuniga             7
90       Roman Colon             4
91     Piper Carroll             3

[92 rows x 2 columns]

In [18]:
# Absent employee
# no any absenet
ab=(
    final_df[final_df["Status"]=="A"]
    .groupby("Name").size()
)
ab

Series([], dtype: int64)

In [19]:
final_df

     Employee Code                 Name        Date Status      Month
1         Atq -406        Thanos Thakur  2022-04-01      P   Apr 2022
2         Atq -462         Jarvis Singh  2022-04-01      P   Apr 2022
3         Atq -411        Nevaeh Waller  2022-04-01      P   Apr 2022
4         Atq -398           Bo Cordova  2022-04-01      P   Apr 2022
5         Atq -438      Mekhi Singleton  2022-04-01      P   Apr 2022
...            ...                  ...         ...    ...        ...
7587      Atq -405           Chris Frye  2022-06-30    WFH  June 2022
7619      Atq -459       Leslie Navarro  2022-06-30    WFH  June 2022
7621      Atq -350  Alexander Davenport  2022-06-30    WFH  June 2022
7623      Atq -374    Kaley Fitzpatrick  2022-06-30    LWP  June 2022
7635      Atq -348       Zaiden Wheeler  2022-06-30    WFH  June 2022

[6553 rows x 5 columns]

In [22]:
final_df

     Employee Code                 Name        Date Status      Month
1         Atq -406        Thanos Thakur  2022-04-01      P   Apr 2022
2         Atq -462         Jarvis Singh  2022-04-01      P   Apr 2022
3         Atq -411        Nevaeh Waller  2022-04-01      P   Apr 2022
4         Atq -398           Bo Cordova  2022-04-01      P   Apr 2022
5         Atq -438      Mekhi Singleton  2022-04-01      P   Apr 2022
...            ...                  ...         ...    ...        ...
7587      Atq -405           Chris Frye  2022-06-30    WFH  June 2022
7619      Atq -459       Leslie Navarro  2022-06-30    WFH  June 2022
7621      Atq -350  Alexander Davenport  2022-06-30    WFH  June 2022
7623      Atq -374    Kaley Fitzpatrick  2022-06-30    LWP  June 2022
7635      Atq -348       Zaiden Wheeler  2022-06-30    WFH  June 2022

[6553 rows x 5 columns]

In [23]:
# here check the all file in the folder
import os

os.listdir()

['.ipynb_checkpoints',
 'Attendance-Sheet-2022-2023.xlsx',
 'Cleaned_Attendance1.xlsx',
 'HR.ipynb',
 'hr_data.csv']

In [27]:
# Here the save the csv file on desktop
final_df.to_csv(
    r"C:\Users\deepa\OneDrive\Desktop\Cleaned_Attendance.csv",
    index=False
)